name: xeus-lite-dev
channels:
  - https://prefix.dev/conda-forge
dependencies:
  - black
  - python-build
  - hatch-jupyter-builder
  - hatch-nodejs-version
  - jupyter-builder >=1.0.0,<2
  - jupyterlab >=4.6,<5
  - mamba <2
  - nodejs
  - pip
  - pytest
  - python
  - requests
  - ruff
  - traitlets
  - typer
  - yarn=3
  - pip:
    - jupyterlite-core >=0.8.0,<0.9.0
    - empack >=5.1.1
